### PR TITLE
Create string.xml (Japanepse)

### PR DESCRIPTION
**Pull request by kaoru-nishida**
please Support Japanese

### CODE REVIEW

**Comment by MartinStyk** [comment]
Thank you very much for your contribution @kaoru-nishida .
I have made several changes in string.xml file which will be included in 2.0.0 release comming out soon. Could you please update your PR to contain all strings, including newly added? 
Then I will merge your PR and japanese will be included in next release.

**Comment by kaoru-nishida** [comment]
Yes. I'll update my PR to contain all strings, including newly added tomorrow(2017-12-16)
because I'm besy to exams now

**Comment by kaoru-nishida** [comment]
I'm sorry being late for translate string.xml
I have finished it.

**Comment by MartinStyk** [comment]
Thank you very much, your PR is merged and will be included in next release comming out during january.

**Pull request merged**
